description = "Chandler's blog about programming, languages, compilers, performance, cpus, tech, and everything else."
keywords = [
  'programming',
  'coding',
  'languages',
  'programming languages',
  'compilers',
  'performance',
  'cpus',
  'tech',
]

defaultTheme = "dark"
disableThemeToggle = true

ShowShareButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
ShowBreadCrumbs = false
hideFooter = true

mainSections = ["posts"]

#[label]
#text = "Home"

[homeInfoParams]
  Content = "A blog about programming, languages, compilers, optimization, performance, CPUs, technology, and everything else. Why use 50 words when 500 will do. =D"

[[socialIcons]]
name = "mastodon"
url = "https://hachyderm.io/@chandlerc"

[[socialIcons]]
name = "github"
url = "https://github.com/chandlerc"

[[socialIcons]]
name = "twitter"
url = "https://twitter.com/chandlerc1024"

[[socialIcons]]
name = "Rss"
url = "index.xml"

[reveal_hugo]
width = 1600
height = 900
margin = 0.08

controls = false

hash = true
hash_one_based_index = true

navigation_mode = "linear"

# Slide count may have no relation to progress, but display the number for folks
# to reference later.
progress = false
slide_number = "c"

transition = "none"

custom_theme = "css/reveal/custom-theme.scss"
custom_theme_compile = true

# We disable the default plugins here to suppress a forced inclusion of a
# default theme that we don't actually want. We'll manually spell out the same
# plugin sources below.
load_default_plugins = false

raw_initialize_options = "highlight: { beforeHighlight: beforeHighlightHook, },"

[reveal_hugo.custom_theme_options]
targetPath = "css/reveal/custom-theme.css"
enableSourceMap = true

[[reveal_hugo.plugins]]
name = "RevealMarkdown"
source = "plugin/markdown/markdown.js"
order = 1

[[reveal_hugo.plugins]]
name = "RevealHighlight"
source = "plugin/highlight/highlight.js"
order = 2

[[reveal_hugo.plugins]]
name = "RevealZoom"
source = "plugin/zoom/zoom.js"
order = 3

[[reveal_hugo.plugins]]
name = "RevealNotes"
source = "reveal-js/plugin/notes/notes.js"
order = 4
verbatim = true
